on:
  push:
    branches:
      - main

name: Build and Deploy
concurrency: self-hosted

jobs:
  release:
    name: Build and Deploy
    env:
      PROJECT_NAME_UNDERSCORE: hmdl
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build Code
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Unload Existing Server
        run: sudo /bin/launchctl unload -w /Library/LaunchDaemons/hmdl.plist
        continue-on-error: true
      
      - name: Copy server to install directory
        run: |
          rm -rf ~/hmdl/bin/* &&
          cp -r target/release/* ~/hmdl/bin/ &&
          echo "New binary installed hash:`git rev-parse --short HEAD`" >> ~/hmdl/log/stdout.txt
      - name: Reenable Server
        run: sudo /bin/launchctl load -w /Library/LaunchDaemons/hmdl.plist
