on:
  push:
    branches:
      - main

name: Build and Deploy
concurrency: self-hosted

jobs:
  release:
    name: Build and Deploy
    env:
      PROJECT_NAME_UNDERSCORE: hearthstone-server
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build Code
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Disable Existing Server
        run: sudo /bin/launchctl disable system/local.hearthstone.server
      - name: Shutdown Existing Server
        run: sudo /bin/launchctl stop local.hearthstone.server
        continue-on-error: true
      - name: Copy server to install directory
        run: |
          rm -rf ~/hearthstone-server/bin/* &&
          cp -r target/release/* ~/hearthstone-server/bin/
      - name: Reenable Server
        run: sudo /bin/launchctl enable system/local.hearthstone.server
